#!/usr/bin/env python

import sys

from rqt_virtual_joy.virtual_joy_module import MyPlugin
from rqt_gui.main import Main

plugin = 'hexapod_control_panel'
main = Main(filename=plugin)
sys.exit(main.main(standalone=plugin))